name: Ruby on Rails CI

on:
  push:
    branches: 
    - development

jobs:
  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        # Provide the password for postgres
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        # Set health checks to wait until postgres has started
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: "Init repository"
        uses: actions/checkout@v2


      - name: Wait for database to be ready
        run: |
          while ! pg_isready -h localhost -p 5432 -U postgres; do
            sleep 2
          done

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install

      - name: Setup database
        env:
          RAILS_ENV: test
          POSTGRES_HOST: postgres
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
          DATABASE_URL: postgres://postgres:@localhost:5432/${{ secrets.POSTGRES_DB }}
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create
          bundle exec rake db:migrate

      - name: Run Tests
        env:
          RAILS_ENV: test
          POSTGRES_HOST: postgres
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          DATABASE_URL: postgres://postgres:@localhost:5432/${{ secrets.POSTGRES_DB }}
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: bundle exec rspec
